### ISSUE TITLE
Does it work nicely with Youshido/GraphQL

### ISSUE THREAD

**Issue by dilab** [overblog/dataloader-php#15]
Does it support https://github.com/Youshido/GraphQL?

**Comment by mcg-web** [comment]
not right now but writing a dedicate promiseAdapter implementing PromiseAdapterInterface should make this possible...

**Comment by dilab** [comment]
@mcg-web thanks.

**Comment by mcg-web** [comment]
I'm not custom with Youshido implementation and this doesn't look to be a need right now, so I'm closing this feel free to open if this is actually a need.
