### ISSUE TITLE
Problem with 1:N relation

### ISSUE THREAD

**Issue by enumag** [overblog/dataloader-php#18]
The problem is apparent even in the readme of this package:

```php
$userType = new ObjectType([
  'name' => 'User',
  'fields' => function () use (&$userType, $userLoader, $dbh) {
     return [
            'name' => ['type' => Type::string()],
            'bestFriend' => [
                'type' => $userType,
                'resolve' => function ($user) use ($userLoader) {
                    $userLoader->load($user['bestFriendID']);
                }
            ],
            'friends' => [
                'args' => [
                    'first' => ['type' => Type::int() ],
                ],
                'type' => Type::listOf($userType),
                'resolve' => function ($user, $args) use ($userLoader, $dbh) {
                    $sth = $dbh->prepare('SELECT toID FROM friends WHERE fromID=:userID LIMIT :first');
                    $sth->bindParam(':userID', $user['id'], PDO::PARAM_INT);
                    $sth->bindParam(':first', $args['first'], PDO::PARAM_INT);
                    $friendIDs = $sth->execute();

                    return $userLoader->loadMany($friendIDs);
                }
            ]
        ];
    }
]);
```

Now if I ask for several users + their best friends it will work nicely. All best friends will be loaded together.

```
{
  users {
    name
    bestFriend {
      name
    }
  }
}
```

However if I ask for several users + 5 friends for each user then the query `SELECT toID FROM friends WHERE fromID=:userID LIMIT :first` will be repeated separately for each user instead of making just one query. So the N+1 problem is not really gone, just more hidden.

```
{
  users {
    name
    friends(first: 5) {
      name
    }
  }
}
```

How should I eliminate this behavior?

**Comment by mcg-web** [comment]
This example show how to fix n+1 calls for user friends, you can modify your loader to accepts user ID and return friends array for this user...

**Comment by mcg-web** [comment]
Closing this, feel free to reopen if needed.

**Comment by Sh1d0w** [comment]
@mcg-web Can you please explain what do you mean by that? If you pass a single id, the loader will expect a single request returned, not an array?

Can you provide example code how to handle relations like in the example above?
