### ISSUE TITLE
Naming confusion

### ISSUE THREAD

**Issue by akomm** [overblog/dataloader-php#20]
The Interface naming generates a knot in my head everytime I want to do something, even though I understand the inner working of the two:

- Overblog\PromiseAdapter\PromiseAdapterInterface
- GraphQL\Executor\Promise\PromiseAdapter

The first is used to promise the IDs, while the second is then'd with all ids to resolve the final data usind the batch load callback. Or is it not?

All the overblog related packages are very helpful, but regarding the naming I always get knots in my head ;(

The second comes from the webonyx project and makes sense. It is an interface for a promise based result. The first should maybe indicate it being an aggregate or higher order or collector promise (something that direction)?

I know, naming things is not easy :( .

http://hilton.org.uk/blog/why-naming-things-is-hard

**Comment by mcg-web** [comment]
`Overblog\PromiseAdapter\PromiseAdapterInterface` promise adapter is just an interface to help abstract Promises between different libs for dataloaders. `GraphQL\Executor\Promise\PromiseAdapter` has the same function but for graphql. GraphQL is not a requirements for this lib. When I introduce `GraphQL\Executor\Promise\PromiseAdapter` on graphql I try to make this a independent  lib but was rejected :D

**Comment by akomm** [comment]
So you made instead of inheritance a composition to serve different adapters under the PromiseAdapterInterface so you are not dependend on a certain lib's interface.

**Comment by mcg-web** [comment]
No need to use promise adapter to create promise. Only requirement is to return a supported promise for the adapter you are using.

**Comment by akomm** [comment]
Thank you.

I still use  the PromiseAdapterInterface, so my service does not need two adapters injected - its confusing ;) 

But good to know.
