### ISSUE TITLE
How to ensure keys get mapped to the correct objects?

### ISSUE THREAD

**Issue by KevinAsher** [overblog/dataloader-php#23]
Hi, I'm not sure if it's an issue or just a misunderstanding. Suppose we have the following query:

```graphql
{
  u1: user (id: 25) {
    id
  }
  u2: user (id: 30) {
    id
  } 
  u3: user (id: 20) {
    id
  }
}
```

And our batchLoadFn is something like this (Laravel):
```php
...
$userLoader = new DataLoader(function ($ids) use ($promiseAdapter) {
  $collection = User::whereIn('id', $ids)->get();

  return $promiseAdapter->createFulfilled($collection);
}, $promiseAdapter)
```

Since there's no key mapping between the collection items and the keys, this will give us the following incorrect result (the resulting user objects are in the wrong order):

```json
{
  "data": {
    "u1": {
      "id": "20"
    },
    "u2": {
      "id": "25"
    },
    "u3": {
      "id": "30"
    }
  }
}
```

How can i ensure the keys are mapped to correct objects?

**Comment by mcg-web** [comment]
Hi, the order of the objects must be exactly the same with the order of the keys...

**Comment by mcg-web** [comment]
I forgotten this [section of the doc](https://github.com/overblog/dataloader-php/blob/master/README.md#batch-function) will help you understand.

**Comment by KevinAsher** [comment]
Thanks @mcg-web, finally getting the hang of it! 👍
