### ISSUE TITLE
Incompatibility with experimental Executor

### ISSUE THREAD

**Issue by enumag** [overblog/dataloader-php#30]
Related to https://github.com/webonyx/graphql-php/issues/397.

Webonyx 0.13 has a new experimental (but faster) [Executor implementation](https://github.com/webonyx/graphql-php/blob/master/src/Experimental/Executor/CoroutineExecutor.php). However it seems that the custom [promise adapter](https://github.com/overblog/dataloader-php/blob/master/lib/promise-adapter/src/Adapter/WebonyxGraphQLSyncPromiseAdapter.php) from this package is not compatible with it. When they are used together, some resolve functions get a `GraphQL\Executor\Promise\Promise` as their first parameter instead of the resolved value.

**Comment by mcg-web** [comment]
We should first make the bundle support this new experimental executor after make this lib support it also. The work already in progress anyway :+1:

**Comment by mcg-web** [comment]
The issue seem to come from the executor itself webonyx/graphql-php#486, we should maybe re-give it a try after fixing this.

**Comment by enumag** [comment]
Thanks. I'll try it again when the PR is merged.

**Comment by enumag** [comment]
Everything seems to work on my end with that fix. Thank you!
