### ISSUE TITLE
Context for fetching

### ISSUE THREAD

**Issue by danut007ro** [overblog/dataloader-php#33]
Hello. I need to load data from an elasticsearch instance. All is working fine, but my issue is about overfetching of data and not using it in response (for instance, querying for name field also reads a description field which is not needed actually).

So I was thinking about something like a context for every load. The queue will be grouped by unique context values and requests will be made for each of it. In my case, the context will be the fields that I need.

If this sounds ok, I can try a pull request. Or maybe there is another way if doing this which I'm not aware of.

Thanks.

**Comment by murtukov** [comment]
@danut007ro Hi. Please provide someone examples, because  it‘s not clear  what are you trying to do

**Comment by artursvonda** [comment]
I would recommend against this. But there's a way around this without changing API. Keys don't have to be scalars. You can have objects or arrays as keys. So you could do `->load(['id' => 'object id', 'fields' => ['id', 'name'])` (although be mindful when using objects as they are compared by identity). Then in the batching functions you can execute the requests however you want.
From my experience, it's best to return consistent data shape for all requests to the loader. Fetching extra field or two is a small price for the simplicity gained.
