### ISSUE TITLE
Correct use without deprecated `GraphQL::execute()`?

### ISSUE THREAD

**Issue by vhenzl** [overblog/dataloader-php#39]
`GraphQL::execute()` [has been deprecated](https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md#deprecated-graphqlgraphqlexecute) many versions ago.

There are two examples of how to use _dataloaders_ with `webonyx/graphql-php` (I'm aware of):

A test in this project:

https://github.com/overblog/dataloader-php/blob/9a3be9096fd81bc33fe0a1fe6cfb7f2609cf5735/tests/Functional/Webonyx/GraphQL/TestCase.php#L84

And https://github.com/mcg-web/sandbox-dataloader-graphql-php. But both use this deprecated API.

**What's the correct use without deprecated `GraphQL::execute()`** (particularly in combination with the "native" `SyncPromise`)?

`GraphQL::executeQuery()` can't be use as it internally [always uses](https://github.com/webonyx/graphql-php/blob/8ee8eec1bb312c5e302d7ba9a9216bf6ad9b851e/src/GraphQL.php#L91) `GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter\SyncPromiseAdapter` instance, not `Overblog\DataLoader\Promise\Adapter\Webonyx\GraphQL\SyncPromiseAdapter` instance set with `GraphQL::setPromiseAdapter()` and it's execution results in _"GraphQL\Error\InvariantViolation: Could not resolve promise"_ error.

Assuming from [this comment](https://github.com/webonyx/graphql-php/blob/8ee8eec1bb312c5e302d7ba9a9216bf6ad9b851e/src/Executor/Executor.php#L95-L97), the whole use of `GraphQL::setPromiseAdapter()` should be considered deprecated and for all cases that don't use `GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter\SyncPromiseAdapter`, `GraphQL::promiseToExecute()` should be used.

Given these adapters:

```php
use Overblog\DataLoader\Promise\Adapter\Webonyx\GraphQL\SyncPromiseAdapter;
use Overblog\PromiseAdapter\Adapter\WebonyxGraphQLSyncPromiseAdapter;

$graphQLPromiseAdapter = new SyncPromiseAdapter();
$dataLoaderPromiseAdapter = new WebonyxGraphQLSyncPromiseAdapter($graphQLPromiseAdapter);
```

I see two possible solutions. Either:

```php
$promise = GraphQL::promiseToExecute($graphQLPromiseAdapter, $schema, $query /* ... */);
$result = $graphQLPromiseAdapter->wait($promise);
```

which kinda replicates what `GraphQL::execute()` does, or:

```php
$promise = GraphQL::promiseToExecute($graphQLPromiseAdapter, $schema, $query /* ... */);
$result = DataLoader::await($promise)->toArray();    
```

Is that correct? Both works and seems to work equally. Is there any real difference between them? Any pros and cons using one over the other?

**Comment by vhenzl** [comment]
#36 likely related.

**Comment by vhenzl** [comment]
The second option with `DataLoader::await()` doesn't seem to be correct. It can fail with _"Found no active DataLoader instance"_ error if no field returning a promise queried - for instance during introspection.

**Comment by simPod** [comment]
I have dropped deprecated api in tests in #51
