### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by vhenzl** [overblog/dataloader-php#40]
The library should be updated to support PHP 8.

Doing so, older PHP versions could be removed, tests for PHP 7.3 should be fixed (failing currently) and added for PHP 7.4. Also, dev dependencies should be bumped - `webonyx/graphql-php` v0.11 vs current v14.

I'm happy to prepare a PR…

**Comment by mcg-web** [comment]
@vhenzl a PR will be welcome for this change :+1: .
